name: docs
on:
  push:
    branches:
      - main
jobs:
  build:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm ci --no-audit
      - run: npm run create-docs
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - uses: JamesIves/github-pages-deploy-action@v4.2.3
        with:
          folder: docs
          branch: gh-pages
          target-folder: ${{ steps.package-version.outputs.current-version }}
